M48
; DRILL file KiCad 10.0.6 date 2026-09-23T09:43:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-23T09:43:20+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.300
%
G90
G05
T1
X42.4Y59.89
X42.4Y54.11
T2
X-22.857Y64.5
X-21.157Y64.5
T3
X-2.55Y64.8
X5.43Y64.8
T4
X-28.15Y21.2
X27.85Y16.0
M30
