#!/usr/bin/env python3
# MSX PICOVERSE PROJECT
# (c) 2026 Cristiano Goncalves
# The Retro Hacker
#
# gen_romdb.py - Convert the Explorer firmware ROM database (pico/explorer/romdb.h)
# into the plain text table read by the openMSX add-on (picoverse2350.tcl), so
# both detect the same mappers. One line per ROM: "<sha1> <mapper code>".
#
# Usage: python gen_romdb.py [romdb.h] [output.txt]
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version. See <https://www.gnu.org/licenses/>.

import re
import sys
from pathlib import Path

here = Path(__file__).resolve().parent
src = Path(sys.argv[1]) if len(sys.argv) > 1 else here.parent / "pico" / "explorer" / "romdb.h"
dst = Path(sys.argv[2]) if len(sys.argv) > 2 else here / "share" / "extensions" / "PicoVerse_2350" / "romdb.txt"

text = src.read_text(encoding="utf-8")
count = int(re.search(r"#define ROMDB_COUNT (\d+)", text).group(1))
sha_block = text[text.index("romdb_sha1s"):text.index("romdb_mappers")]
digests = ["".join(b[2:] for b in re.findall(r"0x[0-9a-fA-F]{2}", row))
           for row in re.findall(r"\{([^{}]*)\}", sha_block)]
map_block = text[text.index("romdb_mappers"):]
map_block = map_block[map_block.index("{") + 1:map_block.index("};")]
mappers = [int(v, 0) for v in re.findall(r"0x[0-9a-fA-F]+|\d+", map_block)]

if len(digests) != count or len(mappers) != count or any(len(d) != 40 for d in digests):
    sys.exit(f"{src}: expected {count} entries, found {len(digests)} digests and {len(mappers)} mappers")

header = [line for line in text.splitlines()[:4] if line.startswith("//")]
lines = ["# Generated by gen_romdb.py from pico/explorer/romdb.h, do not edit."]
lines += ["# " + line[2:].strip() for line in header]
lines += [f"{d.lower()} {m}" for d, m in zip(digests, mappers)]
dst.parent.mkdir(parents=True, exist_ok=True)
dst.write_text("\n".join(lines) + "\n", encoding="ascii", newline="\n")
print(f"{dst}: {count} entries")
